"""Add website and custom_fields to user_places

Revision ID: 002_add_place_fields
Revises: 3ba4c3d04330
Create Date: 2025-09-28 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_place_fields'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add website column to user_places table
    op.add_column('user_places', sa.Column('website', sa.String(), nullable=True))

    # Add custom_fields column to user_places table
    op.add_column('user_places', sa.Column('custom_fields', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove custom_fields column from user_places table
    op.drop_column('user_places', 'custom_fields')

    # Remove website column from user_places table
    op.drop_column('user_places', 'website')
    # ### end Alembic commands ###